language: go
go:
  - 1.x

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
  - golangci-lint run ./...
  - go test ./test/... -v -race -coverprofile=coverage.txt -covermode=atomic  -coverpkg=./...
after_success:
  - bash <(curl -s https://codecov.io/bash)