language: go
go:
  - 1.16.x
  - 1.x
  - master

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
  - go test ./test -v -race -coverprofile=coverage.txt -covermode=atomic  -coverpkg=./...
  - golangci-lint run ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)