language: go
go:
  - 1.16.x
  - 1.x
  - master

script:
  - go test ./test -v -race -coverprofile=coverage.txt -covermode=atomic  -coverpkg=./...
after_success:
  - bash <(curl -s https://codecov.io/bash)